name: NationWarPlugin
version: 1.0
main: com.yourname.nationwar.NationWarPlugin
api-version: 1.19
commands:
  personalchest: //한국어
    description: 개인 창고를 엽니다.
    usage: /개인창고
  personalchest: //영어
    description: 개인 창고를 엽니다.
    usage: /personalchest
