name: NationWarPlugin
version: 1.0
main: com.yourname.nationwar.NationWarPlugin
api-version: 1.20.1 // 현재 사용 중인 Minecraft 버전에 맞춤

commands:
  personalchest:
    description: 
      한국어: 개인 창고를 엽니다.
      영어: Opens your personal chest.
    usage:
      한국어: /개인창고
      영어: /personalchest
